# Generated by Django 4.2 on 2025-05-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_donation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='returned',
        ),
        migrations.AddField(
            model_name='rental',
            name='last_payment_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_months',
            field=models.PositiveIntegerField(default=1, help_text='Number of months for rental (1-12)'),
        ),
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('ongoing', 'Ongoing'), ('returning', 'Returning'), ('returned', 'Returned')], default='preparing', max_length=20),
        ),
    ]
